Avoid including opencl.h from hipcc
On powerpc at least, that brings conflicts with including
/usr/include/CL/cl_platform.h:

/usr/include/CL/cl_platform.h:385:12: error: unknown type name '__vector'
  385 |    typedef __vector unsigned char     __cl_uchar16;